# config.yaml


# SYSTEM PARAMETERS
L: 4
bond_dimension: 2
t_max: 1.0
initial_state_kind: "all_plus" # "all_zeros" or "all_plus"

# HAMILTONIAN MODEL
hamiltonian_type: "custom"  # "uniform_xyz" or "general_local_zz" or "custom"

x_fields: True
y_fields: False
z_fields: True

# NOISE SETTINGS
use_noisy_dynamics: False  # Set to True to use Lindblad dynamics
learn_noise_params: False  # Whether to learn noise rates
noise_model: "global"       # "global" (2 params) or "local" (2L params)

# Initial guesses for noise (used if learn_noise_params=True)
gamma_dephasing_init: 0   # Initial dephasing rate (global or per-qubit)
gamma_damping_init: 0    # Initial damping rate (global or per-qubit)

model: 'manual' # 'manual', 'pytorch', 'tensorkrowch'

# TRAINING PARAMETERS
dt: 0.01
N_epochs: 10
learning_rate: 0.01
print_every: 100

# HAMILTONIAN INITIAL GUESS
Jx_init: 0.5 
Jy_init: 0.5 
Jz_init: 0.5
hx_init: 0.0 
hy_init: 0.0 
hz_init: 0.5
hx_list_init: [0.5, 0.5, 0.5, 0.5] #Has to be of length L
hz_list_init: [0, 0, 0] #Has to be of length L
Jzz_list_init: [0.5, 0.5, 0.5, 0.5]  #Has to be of length L -1
INIT_PERTURB_SCALE: 0.0

# NDE ARCHITECTURE
MODEL_TYPE: "white"
NN_MODEL_TYPE: "time_dependent"
NN_hidden_sizes: [64]
learn_theta: True

# CURRICULUM
PHASE1_SPLIT: 0.4
PHASE2_SPLIT: 0.4
PHASE3_SPLIT: 0.2
lambda_reg: 0.1
noise_reg: 0.001  # Regularization for noise parameters
seed_init: 4321
T_extrapolate_factor: 5.0
